### ISSUE TITLE
Stylus support

### ISSUE THREAD

**Issue by 0pt1m1z3r** [yenshih/style-resources-loader#1]
Hi! Great loader!
I added it to nuxt.js: https://github.com/nuxt/nuxt.js/pull/2172
Could you add a Stylus?

**Comment by yenshih** [comment]
Sure! I'd glad to add stylus support ASAP.

**Comment by yenshih** [comment]
It's currently supports Stylus :) @0pt1m1z3r 
Documentation will be updated in a few days.

**Comment by 0pt1m1z3r** [comment]
Thank you!
