### ISSUE TITLE
vue-cli2.x中导入less变量文件失败

### ISSUE THREAD

**Issue by TTtuntuntutu** [yenshih/style-resources-loader#11]
你好，项目有点旧了，用的vue-cli2.x搭建，预处理器用的less，想为组件全局导入变量、mixin资源。

这里是 build/utils.js 内loaders的配置文件代码：[配置文件代码](https://jsbin.com/vicesevuji/edit?html,js,output)；是按照说明文档中的example去配置的....

但是启动项目在组件内使用全局变量less文件内的变量，还是没有识别。

求告知阿~另外在网上搜索这个问题，出现最多的还是推荐使用sass-resources-loader，是推广不够吗hhhhhh

**Comment by yenshih** [comment]
看起来不像有什么问题啊，我建议你可以这样
 - 把最终 webpack 使用的配置 log 或者 stringify 后 log 出来，看看 loader 是否确实配置了
 - 如果配置了，控制台里看看 source 里的 less 文件效果如何，正常来说是会插入的
 - 如果没有插入，检查下那个路径是否存在
 - 把关联的几个文件贴上来看看，jsbin 不太容易看

库本身应该没太大问题，毕竟用的人不算少，我倾向于还是配置错了。
关于，其实并没有推广，hhhh

**Comment by TTtuntuntutu** [comment]
感谢回复。
- 在开发环境下输出了一下webpack loader的配置，loader应该是存在的
```javascript
[ 'vue-style-loader',
  { loader: 'css-loader',
    options: { minimize: false, sourceMap: true } },
  { loader: 'less-loader', options: { sourceMap: true } },
  { loader: 'style-resources-loader',
    options:
     { patterns:
        'D:\front-end\bangsun_projects\decision-maker-mgr\decision-maker-mgr-ui\src\style\theme\custom.less',
       injector: 'append' } } ]
```
- 查看了一下控制台sources里的less文件，和项目里写的是一样的，没有插入路径对应的变量文件
- 在Vue组件内部使用还是不识别变量，变量文件路径写的是相对路径：`path.resolve(__dirname, "../src/style/theme/custom.less")`
- 文件
[utils.txt](https://github.com/yenshih/style-resources-loader/files/3053150/utils.txt)
[webpack.dev.config.txt](https://github.com/yenshih/style-resources-loader/files/3053155/webpack.dev.config.txt)

**Comment by yenshih** [comment]
似乎并没有什么错……先确保版本是最新版，然后去 `node_modules` 里找源码打 log 调试吧，帮不上忙了

**Comment by a124779683** [comment]
> 感谢回复。
> 
> * 在开发环境下输出了一下webpack loader的配置，loader应该是存在的
> 
> ```js
> [ 'vue-style-loader',
>   { loader: 'css-loader',
>     options: { minimize: false, sourceMap: true } },
>   { loader: 'less-loader', options: { sourceMap: true } },
>   { loader: 'style-resources-loader',
>     options:
>      { patterns:
>         'D:\front-end\bangsun_projects\decision-maker-mgr\decision-maker-mgr-ui\src\style\theme\custom.less',
>        injector: 'append' } } ]
> ```
> 
> * 查看了一下控制台sources里的less文件，和项目里写的是一样的，没有插入路径对应的变量文件
> * 在Vue组件内部使用还是不识别变量，变量文件路径写的是相对路径：`path.resolve(__dirname, "../src/style/theme/custom.less")`
> * 文件
>   [utils.txt](https://github.com/yenshih/style-resources-loader/files/3053150/utils.txt)
>   [webpack.dev.config.txt](https://github.com/yenshih/style-resources-loader/files/3053155/webpack.dev.config.txt)

我也有一个很老的项目，配置跟你一模一样，用的你配置成功了
