### ISSUE TITLE
Conflicts with mini-css-extract-plugin

### ISSUE THREAD

**Issue by yenshih** [yenshih/style-resources-loader#12]
![image](https://user-images.githubusercontent.com/14069488/55537275-664c6a80-56ee-11e9-9f5e-63fefc60bcb9.png)

**Comment by yenshih** [comment]
It also needs to ensure at least one `\n` character at the end of each resource.

**Comment by frontHu** [comment]
> It also needs to ensure at least one `\n` character at the end of each resource.

how to resolve the issue？
