### ISSUE TITLE
mixin和variables会输出到style标签内，而且有很多重复项（一个组件产生一个style）

### ISSUE THREAD

**Issue by ideagay** [yenshih/style-resources-loader#16]
// vue.config.js
rules: [
                {
                    test: /\.(css|less)$/,
                    use: [
                        {
                            loader: 'style-resources-loader',
                            options: {
                                patterns: [
                                    path.resolve(__dirname, './node_modules/@souche-ui/lemon/less/global.less'),
                                    path.resolve(__dirname, './src/assets/style/mixin.less')
                                  
                                ]
                            }
                        }
                    ]
                }
            ]

// mixin.less
.flex-between() {
    display: flex;
    justify-content: space-between;
    align-items: center;
}

![image](https://user-images.githubusercontent.com/4416844/60561645-d36faa80-9d86-11e9-8081-3ce3ca57c33f.png)
不想让这些mixin或者变量文件被输出到style标签内

**Comment by yenshih** [comment]
请问你有添加 less-loader 么？

**Comment by ideagay** [comment]
less-loader有添加

**Comment by yenshih** [comment]
@ideagay 那 mixin 和变量会被编译，本来就不会 emit 的，肯定是配错了，检查一下 less-loader 有没有生效

**Comment by ideagay** [comment]
@yenshih vue-cli3.0 生成的项目，less-loader的配置没有暴露出来，默认应该是配置了的，已经安装了less和less-loader，生效是肯定的，组件内的less能正常编译，是需要在vue.config.js中单独再配置下less-loader吗?

**Comment by yenshih** [comment]
@ideagay https://cli.vuejs.org/guide/css.html#automatic-imports
