### ISSUE TITLE
Failed to cache .less files on Win 10 with Webpack 4

### ISSUE THREAD

**Issue by Tao-Oak** [yenshih/style-resources-loader#17]
We used SRL with Webpack 3, and it worked well both on Windows and Ubuntu. After we upgraded Webpack from 3 to 4, there is a significant improvement for incremental build speed on Ubuntu. But for windows, this is not the case. It took ~30s for every incremental build on windows. Through examining the Webpack log and some simple tests, we found that SRL caused .less files to rebuild on every incremental build. Here is the [minimal reproducible repo](https://github.com/Tao-Oak/style-resources-loader-test) with two branches, one use SRL, and one use @import to load the baseStyle.less file.

After some debugging, we found that SRL uses [glob](https://www.npmjs.com/package/glob) to match [the patterns option](https://github.com/yenshih/style-resources-loader#patterns) and returns Unix style file path like `D:/you/path/to/less/file.less`. It then adds this Unix style file path to the dependency list of the current module. While the [needRebuild](https://github.com/webpack/webpack/blob/master/lib/NormalModule.js#L541) method which controls the cache behavior of Webpack uses windows style file path on windows. 

The`needRebuild` method has two parameters: `fileTimestamps` and `contextTimestamps`, which both are `filePath -> timestamps` Map. The keys of these two Maps are windows style file path like `D:\\you\\path\\to\\less\\file.less`, and the values are timestamps when the corresponding file was updated.

Due to the mismatch of these two file path styles, the `needRebuild` method returns false every time and thus .less files rebuild on every incremental build.

**Comment by yenshih** [comment]
Great analysis, will fix it soon. thanks!

**Comment by yenshih** [comment]
Hi! I have spent some time trying to figure out this problem.
It seems webpack has updated a bunch of code in these few days.

Actually I don't have a Windows PC to reproduce. I was just wondering if you could point out how wepack

> controls the cache behavior of Webpack uses windows style file path on windows

Probably related source code:
https://github.com/webpack/loader-runner/blob/master/lib/LoaderRunner.js#L284
https://github.com/webpack/webpack/blob/master/lib/NormalModule.js#L467
https://github.com/webpack/webpack/blob/master/lib/FileSystemInfo.js#L677

**Comment by Tao-Oak** [comment]
For webpack 4, it use the needRebuild method to control the cache behavior, [here](https://github.com/webpack/webpack/blob/v4.41.2/lib/NormalModule.js#L541) is code location of webpack v4.41.2.

For webpack 5, needRebuild was deprecated but use needBuild insteand，[here is the code](https://github.com/webpack/webpack/blob/v5.0.0-beta.9/lib/Module.js#L607).

For the case you don't have a Windows PC to reproduce this problem, I will create a PR to fix it latterly.
