### ISSUE TITLE
Very serious performance issues

### ISSUE THREAD

**Issue by RichieChoo** [yenshih/style-resources-loader#19]
The style-resources-loader solved less Variable undefined problem well. 
But When I add several path in the patterns . I use 8092 MB to run `npm run build`,it throw `Maximum still call stack size exceeded` .

**Comment by yenshih** [comment]
May I have your loader config?

**Comment by RichieChoo** [comment]
Just like this 
![image](https://user-images.githubusercontent.com/17178139/67666571-04fc2980-f9a7-11e9-9435-3e81c2ced242.png)

**Comment by RichieChoo** [comment]
And I know that the plugin in below image also uses ` style-resources-loader` to automatically import files (for colors, variables, mixins...), 
![image](https://user-images.githubusercontent.com/17178139/67667141-2b6e9480-f9a8-11e9-8333-46fd2ea036a4.png)

**Comment by yenshih** [comment]
It's not enough to solve the problem :(
I still need more information, such as error messages and less file content.

**Comment by RichieChoo** [comment]
I'm sorry about it.I found some recursive function in  less file of  my team.
