### ISSUE TITLE
Thank you! This loader is awesome! :D

### ISSUE THREAD

**Issue by phil-lgr** [yenshih/style-resources-loader#3]
Maybe you could ask the folks at ant-design to suggest `style-resources-loader` here: https://ant.design/docs/react/customize-theme

They link to an article which uses `modifyVars`... but your loader is way better since the changes can be picked up by webpack without a restart of the dev-server.

Feel free to close this thank you note 👍

**Comment by yenshih** [comment]
Thank you for your appreciate! I had already made an issue in [#8234](https://github.com/ant-design/ant-design/issues/8234). Not accepted since @yesmeck has wrote a plugin for same purpose :)  Thanks anyway!
