### ISSUE TITLE
"main" in package.json is wrong since 1.4.0

### ISSUE THREAD

**Issue by exreplay** [yenshih/style-resources-loader#30]
The latest update to version 1.4.0 breaks the package because `main` in package.json points to `lib/index.js` which is not present. Since 1.4.0 the `lib` folder has a subfolder `src` and this is where the `index.js` file now lies.

**Comment by ssyz1988** [comment]
+1

**Comment by WinterFete** [comment]
+1

**Comment by KedAyAyA** [comment]
+1

**Comment by yenshih** [comment]
OH...

**Comment by yenshih** [comment]
It seems `baseUrl` in `tsconfig.json` breaks the build process. Fixed in 1.4.1.
