### ISSUE TITLE
今早上来，此包突然不行了，看了下作者是升级了两个版本1.4.0和1.4.1

### ISSUE THREAD

**Issue by jingleding** [yenshih/style-resources-loader#31]
今早上来，此包突然不行了，看了下作者是升级了两个版本1.4.0和1.4.1，但是我的package.json里面是写的"style-resources-loader": "^1.3.3"，为啥会自动去找最新的呢

**Comment by yenshih** [comment]
https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004

重装下试试，1.4.1 应该是可以的
