### ISSUE TITLE
It doesn't work in webpack 5

### ISSUE THREAD

**Issue by Clloz** [yenshih/style-resources-loader#32]
In webpack 5, the resource will not inject to other style file. Both sass and less, if I try to inject a variable to style file, webpack will throw a error `variable is not defined`.

**Comment by yenshih** [comment]
webpack 5 特有的么？有没有一些配置和例子？

**Comment by Clloz** [comment]
十分抱歉，我是自己的路径配置有问题。因为报错一直显示变量未定义，还特地修改成一个不存在的路径还是报一样的变量为定义，所以我就没想到是路径的问题，我以为是 loader 没工作，😂 尴尬。
