### ISSUE TITLE
Import PostCSS .css files

### ISSUE THREAD

**Issue by nathanchase** [yenshih/style-resources-loader#7]
I have mixins, custom-media, and other PostCSS-only features that I'd like to store in a .css file and import them into my components using `style-resources-loader`, but it appears this only works with LESS, SCSS, SASS, and Stylus.

Would it be possible to point it directly to a .css file that contained some PostCSS extended features?

Something like:
```
patterns: [
     path.resolve(__dirname, 'path/to/postcss/mixins/*.css'),
     path.resolve(__dirname, 'path/to/postcss/custommedia/*.css')
],
```
?

**Comment by nathanchase** [comment]
Fantastic! I appreciate it, and look forward to it!

**Comment by yenshih** [comment]
I've bumped it to v1.2.0, hope it helps! @nathanchase

**Comment by nathanchase** [comment]
I couldn't get it to work with custom media queries. Is that beyond the scope of this loader? 

i.e.  **custommedia.css**
```
@custom-media --larger-than-skyscraper (min-width:160px);
@custom-media --larger-than-iphone-se (min-width:374px);
@custom-media --larger-than-mobile (min-width: 414px);
@custom-media --larger-than-phablet (min-width: 550px);
@custom-media --larger-than-leaderboard (min-width:728px);
@custom-media --larger-than-tablet (min-width: 750px);
@custom-media --larger-than-desktop (min-width: 1000px);
@custom-media --larger-than-ipad (min-width: 1024px);
@custom-media --larger-than-desktop-hd (min-width: 1200px);
@custom-media --full-size (min-width: 1440px);
```
and
```
options: {
                    patterns: [
                        path.resolve(__dirname, 'path/to/css/custommedia.css.css'),
                    ]
                }
```
Does it only support variables and mixins specifically?

**Comment by yenshih** [comment]
> Does it only support variables and mixins specifically?

Absolutely not. It just simply insert those resources into your source file.
Maybe you could check if your `patterns` is correct.
`custommedia.css.css` -> `custommedia.css`?

**Comment by nathanchase** [comment]
Ok, I'll take another look and see if I can get it working.
