### ISSUE TITLE
Resolving import url fails on Windows

### ISSUE THREAD

**Issue by yutahaga** [yenshih/style-resources-loader#8]
In CSS, only POSIX path (`../../foo`) is allowed. But on Windows, Windows path (`..\..\foo`) is inserted in CSS, and so resolving import url fails.

* [utils/resolveImportUrl.ts#L25](https://github.com/yenshih/style-resources-loader/blob/master/src/utils/resolveImportUrl.ts#L25)

**Comment by yenshih** [comment]
Thanks for reporting! It's probably a bug.
However, I don't have a Windows PC now (12 a.m. UTC+8).
So maybe I could reproduce and fix this problem tomorrow.

**Comment by yenshih** [comment]
I've just published v1.2.1 to fix this bug. @yutahaga

**Comment by yutahaga** [comment]
@yenshih Thank you for quick response!
It worked fine on my Windows machine.
