### ISSUE TITLE
Support of modules with @ sign

### ISSUE THREAD

**Issue by beostefan** [yenshih/style-resources-loader#9]
Hello,

Thank you for this helpful library! The only issue i have is, that the regular expression for the require statement should also match paths with @ sign in module names. This is quite common in current libraries and unfortunately our own packages within our monorepo are prefixed with @.

For me, the statement should look like this:
`const requireReg = /require\s*\((["'])([\w.\/@]+)(?:\1)\)((?:\.[\w_-]+)*);?/igm;`

Best Regards
Stefan

**Comment by yenshih** [comment]
To import styles from `node_modules`, you need to add `~' as a prefix. That's how `css-loader` work exactly.
```css
@import "~bootstrap/bootstrap.css" // => require('bootstrap/bootstrap.css')
@import "~@scope/style.css" // => require('@scope/style.css')
```
Since there're so many edge cases in resolving url, I'm trying to refactor that part at some time.
Thanks for your kindly feedback! Hope it helps :)
